/**
 * lib/stats.ts
 *
 * Exports a class to get rides organized by month and year
 *
 * This code was generated by Google Gemini
 * I was trying to implement my own, based on my PHP code that does the same thing,
 * but I wasn't getting anywhere.
 *
 */

interface Ride {
	id:       string
	title:    string
	miles:    number
	date:     string
	bike:     string
	buddies?: string
	body:     string
	link:     string
}

interface BikeStats {
  [bike: string]: number; // Bike (string) to miles (number)
}

interface MonthBikeStats {
  [month: number]: BikeStats; // Month (number) to BikeStats
}

interface MonthlyRides {
  [month: number]: Ride[]; // Month is 1-12, values are arrays of Rides
}

interface YearlyRides {
  [year: number]: MonthlyRides; // Year is a number, values are MonthlyRides
}

//  Class RidesByYearMonth
export class RidesByYearMonth {
  private data: YearlyRides = {};

  addRide(year: number, month: number, item: Ride): void {
    if (!this.data[year]) {
      this.data[year] = {};
    }
    if (!this.data[year][month]) {
      this.data[year][month] = [];
    }
    this.data[year][month].push(item);
  }

	// Get rides by year or year month
  getRides(year?: number, month?: number): Ride[] | YearlyRides | MonthlyRides | undefined {
    if (year === undefined) {
      return this.data; // Return all data
    }

    if (month === undefined) {
      return this.data[year]; // Return items for a specific year
    }

    return this.data[year]?.[month]; // Return items for a specific year and month
  }

	// Get stats for a year
	getStats(year: number) : Ride[] {

		let total = 0
		let num = 0
		let long = 0
		const mons = [1,2,3,4,5,6,7,8,9,10,11,12]
		mons.forEach(month => {
			if (this.data[year][month]) {
				this.data[year][month].forEach(ride => {
					num++
					total += ride.miles
					long = ride.miles > long ? ride.miles : long
				})
			}
		})
		const avg = Math.round(total / num)

		return ({
			total: total,
			num:   num,
			long:  long,
			avg:   avg
		})
	}

	// Get bike stats as stats.month.bike = miles for a year
  getBikeStats(year: number) : MonthBikeStats {

 		const stats: MonthBikeStats = {};
  	const mons = [1,2,3,4,5,6,7,8,9,10,11,12]

		mons.forEach(month => {

			stats[month] = {}
			if (this.data[year][month]) {
				this.data[year][month].forEach(ride => {
					const bike = ride.bike
				  const miles = ride.miles

					if (!stats[month][bike]) {
						stats[month][bike] = 0;
    			}

			    stats[month][bike] += miles;
				})
  		}
  	})
  	return stats
  }

	// Get bikes for one year
	getBikes(year: number) : [] {
		const bikes = []
		const mons = [1,2,3,4,5,6,7,8,9,10,11,12]

		mons.forEach(month => {
			if (this.data[year][month]) {
				this.data[year][month].forEach(ride => {
					if (!bikes.includes(ride.bike))
    				bikes.push(ride.bike)
				})
			}
		})
		return bikes;
	}



	// Auto generated, I don't use it
  removeRide(year: number, month: number, itemId: number): boolean {
    if (!this.data[year] || !this.data[year][month]) {
      return false; // Year or month does not exist
    }

    const items = this.data[year][month];
    const index = items.findIndex((item) => item.id === itemId);

    if (index !== -1) {
      items.splice(index, 1);
      return true; // Ride removed successfully
    }

    return false; // Ride not found
  }

  getYears(): number[] {
    return Object.keys(this.data).map(Number).sort((a,b)=> a-b);
  }

  getMonths(year: number): number[] | undefined {
    if (!this.data[year]) {
      return undefined;
    }
    return Object.keys(this.data[year]).map(Number).sort((a,b)=> a-b);
  }

  getAllRides(): Ride[] {
    const allRides: Ride[] = [];
    for (const year in this.data) {
      for (const month in this.data[year]) {
        allRides.push(...this.data[year][month]);
      }
    }
    return allRides;
  }

}
